"""
Email Service - Dispatches escalation emails to sawant.nupur25@gmail.com
when query confidence remains below threshold after max revision attempts.
"""

import json
import logging
import os
import smtplib
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("finance_workflow")

DEFAULT_RECIPIENT = os.getenv("HUMAN_REVIEW_EMAIL", "sawant.nupur25@gmail.com")
ESCALATIONS_DIR = os.getenv("ESCALATIONS_DIR", os.path.join(".", "data", "escalations"))


def send_escalation_email(
    query: str,
    confidence: float,
    issues: list[str],
    revise_count: int,
    draft_answer: str,
    recipient_email: str = DEFAULT_RECIPIENT,
) -> dict[str, Any]:
    """
    Sends an escalation email to the reviewer email address (sawant.nupur25@gmail.com)
    containing full details of the input query, confidence score, flagged issues,
    and draft analysis.

    Supports live SMTP dispatch if SMTP credentials are provided in .env,
    and writes an escalation record to ./data/escalations/ for audit logs.
    """
    timestamp_str = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    file_timestamp = int(time.time())

    subject = "[URGENT] Financial Intelligence Escalation - Human Review Required"

    issues_formatted = (
        "\n".join([f"  - {issue}" for issue in issues])
        if issues
        else "  - No specific issues reported."
    )

    plain_body = f"""===================================================================
FINANCIAL INTELLIGENCE SYSTEM — ESCALATION ALERT
===================================================================
Timestamp: {timestamp_str}
Recipient: {recipient_email}

REASON FOR ESCALATION:
The multi-agent confidence score ({confidence:.2f} / 1.00) did not meet 
the required threshold after {revise_count} revision attempt(s).

-------------------------------------------------------------------
USER INPUT QUERY:
-------------------------------------------------------------------
{query}

-------------------------------------------------------------------
CRITIC REVIEW FINDINGS:
-------------------------------------------------------------------
Confidence Score : {confidence:.2f}
Revision Attempts: {revise_count}
Flagged Issues   :
{issues_formatted}

-------------------------------------------------------------------
LATEST DRAFT ANSWER GENERATED BY AGENTS:
-------------------------------------------------------------------
{draft_answer}

===================================================================
Please review this query manually and provide guidance if necessary.
===================================================================
"""

    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #0f172a; color: #e2e8f0; padding: 20px;">
      <div style="max-width: 600px; margin: 0 auto; background-color: #1e293b; border-radius: 12px; padding: 24px; border: 1px solid #334155;">
        <h2 style="color: #ef4444; margin-top: 0;">⚠️ Financial System Escalation Alert</h2>
        <p style="font-size: 14px; color: #94a3b8;">Human review required for user query.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #334155; font-weight: bold; color: #cbd5e1;">Timestamp:</td>
            <td style="padding: 8px; border-bottom: 1px solid #334155; color: #f8fafc;">{timestamp_str}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #334155; font-weight: bold; color: #cbd5e1;">Confidence Score:</td>
            <td style="padding: 8px; border-bottom: 1px solid #334155; color: #ef4444; font-weight: bold;">{confidence:.2f} / 1.00</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #334155; font-weight: bold; color: #cbd5e1;">Revision Retries:</td>
            <td style="padding: 8px; border-bottom: 1px solid #334155; color: #f8fafc;">{revise_count}</td>
          </tr>
        </table>

        <div style="background-color: #0f172a; padding: 14px; border-rounded: 8px; margin-bottom: 16px;">
          <h4 style="margin: 0 0 8px 0; color: #38bdf8;">Original User Query:</h4>
          <p style="margin: 0; font-size: 13px; color: #f1f5f9;">{query}</p>
        </div>

        <div style="background-color: #0f172a; padding: 14px; border-rounded: 8px; margin-bottom: 16px;">
          <h4 style="margin: 0 0 8px 0; color: #f59e0b;">Flagged Critic Issues:</h4>
          <pre style="margin: 0; font-size: 12px; color: #fca5a5; white-space: pre-wrap;">{issues_formatted}</pre>
        </div>

        <div style="background-color: #0f172a; padding: 14px; border-rounded: 8px;">
          <h4 style="margin: 0 0 8px 0; color: #a78bfa;">Draft Specialist Answer:</h4>
          <div style="font-size: 12px; color: #cbd5e1; white-space: pre-wrap;">{draft_answer}</div>
        </div>
      </div>
    </body>
    </html>
    """

    # 1. Save escalation audit file to disk
    os.makedirs(ESCALATIONS_DIR, exist_ok=True)
    log_filename = f"escalation_{file_timestamp}.json"
    log_filepath = os.path.join(ESCALATIONS_DIR, log_filename)

    escalation_record = {
        "timestamp": timestamp_str,
        "recipient": recipient_email,
        "query": query,
        "confidence": confidence,
        "revise_count": revise_count,
        "issues": issues,
        "draft_answer": draft_answer,
    }

    try:
        with open(log_filepath, "w", encoding="utf-8") as f:
            json.dump(escalation_record, f, indent=2)
        logger.info(f"Escalation log written to {log_filepath}")
    except Exception as e:
        logger.error(f"Failed to write escalation log: {e}")

    # 2. Attempt SMTP transmission if SMTP settings are in environment
    smtp_server = os.getenv("SMTP_SERVER", "").strip()
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USERNAME", "").strip()
    smtp_password = os.getenv("SMTP_PASSWORD", "").strip() or os.getenv("SMTP_APP_PASSWORD", "").strip()
    smtp_use_ssl = os.getenv("SMTP_USE_SSL", "true" if smtp_port == 465 else "false").strip().lower() in {"1", "true", "yes", "on"}

    if not smtp_server and recipient_email.lower().endswith("@gmail.com"):
        smtp_server = "smtp.gmail.com"
        if smtp_port == 587:
            smtp_use_ssl = False

    sent_via_smtp = False
    delivery_message = "Escalation notification logged locally; no email was sent."
    if smtp_server and smtp_user and smtp_password:
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = smtp_user
            msg["To"] = recipient_email

            msg.attach(MIMEText(plain_body, "plain"))
            msg.attach(MIMEText(html_body, "html"))

            if smtp_use_ssl:
                with smtplib.SMTP_SSL(smtp_server, smtp_port, timeout=10) as server:
                    server.login(smtp_user, smtp_password)
                    server.sendmail(smtp_user, [recipient_email], msg.as_string())
            else:
                with smtplib.SMTP(smtp_server, smtp_port, timeout=10) as server:
                    server.ehlo()
                    if server.has_extn("STARTTLS"):
                        server.starttls()
                        server.ehlo()
                    server.login(smtp_user, smtp_password)
                    server.sendmail(smtp_user, [recipient_email], msg.as_string())

            logger.info(f"Escalation email successfully sent to {recipient_email}")
            sent_via_smtp = True
            delivery_message = f"Escalation email dispatched to {recipient_email}."
        except Exception as e:
            logger.warning(
                f"SMTP email dispatch failed ({e}). Logged locally to {log_filepath}"
            )
            delivery_message = (
                f"SMTP delivery failed for {recipient_email}; the escalation was logged locally at {log_filepath}."
            )
    else:
        logger.warning(
            "SMTP not configured for escalation mail delivery. "
            "Set SMTP_SERVER, SMTP_USERNAME, and SMTP_PASSWORD in your environment or .env file. "
            f"Escalation was logged locally to {log_filepath}."
        )
        delivery_message = (
            "SMTP is not configured, so the escalation was logged locally and no email was sent. "
            "Add SMTP_SERVER, SMTP_USERNAME, and SMTP_PASSWORD (or SMTP_APP_PASSWORD for Gmail) to enable email delivery."
        )

    return {
        "status": "escalated",
        "recipient": recipient_email,
        "sent_via_smtp": sent_via_smtp,
        "email_sent": sent_via_smtp,
        "log_file": log_filepath,
        "message": delivery_message,
    }
