

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "a551c388963a2f403f8fb9d8dc903506cbe1ca7bf489d44eb378987fbc427dc4"
expose_tokens = ["access"]

[auth.auth0]
client_id = "jbou043FS30WMGkcEanZXq4VdYMKbS8d"
client_secret = "9YVJSiPRpu_ydXKXamKYMEiAdxyh4O_hdxBfqyLFRsHeDCQ_fzfWPTemutb1ftui"
server_metadata_url = "https://nupursawant.us.auth0.com/.well-known/openid-configuration"
client_kwargs = { "audience" = "https://api.finance-intelligence.com" }